#!/usr/bin/env ruby
#
# Put clients in the clients.json file.
require 'json'

path =  File.expand_path(File.dirname(__FILE__))
clients_file = ARGV[1] ? ARGV[1] : "clients.json"

file = File.read("#{path}/#{clients_file}")
hash = JSON.parse(file)

def up?(ip)
  result = `ping -c 1 #{ip}`
  if $?.exitstatus == 0
    true
  else
    false    
  end
end

case ARGV[0]
when "shutdown"
  hash["clients"].each {|client|
    puts "Shutdown #{client['name']}..."
    `ssh root@#{client['ip']} 'shutdown -P now'` if up?(client['ip'])
  }
when "startup"
  hash["clients"].each {|client|
    puts "Startup #{client['name']}..."
    `wakeonlan #{client['mac']}`
  }
when "status"
  puts "Check status of each client"
  hash["clients"].each {|client|
    status = up?(client['ip']) ? "up" : "down"
    puts "#{client['name']} is #{status}"
  }
else
  puts "Usage: ./tc-control command <file>
  \nCommands
  startup\tStart thin clients in clients.json
  shutdown\tShutdown clients in clients.json
  status\tCheck if clients are up or down.

  <file> is optional - if you have a subset of
  thin clients you want to control enter a file here."
end

