#!/usr/bin/env ruby
#
# Put clients in the clients.json file.
require 'json'

file = File.read('clients.json')
hash = JSON.parse(file)

def up?(ip)
  result = `ping -c 1 #{ip}`
  if $?.exitstatus == 0
    puts
    true
  else
    puts "Already down"
    false    
  end
end

case ARGV[0]
when "shutdown"
  hash["clients"].each {|client|
    print "Shutdown #{client['name']}..."
    `ssh root@#{client['ip']} 'shutdown -P now'` if up?(client['ip'])
  }
when "startup"
  hash["clients"].each {|client|
    puts "Startup #{client['name']}..."
    `wakeonlan #{client['mac']}`
  }
else
  puts "Usage: ./tc-control <startup/shutdown>"
end

